### ISSUE TITLE
help implemention of the indent in files twig

### ISSUE THREAD

**Issue by lalonso-dev** [nelsyeung/twig.vim#3]
Hello I have been using the plugin for a while, but I have not found the way how I can apply the twig files identation in the documentation there is no mention of any extra configuration for this or if you must run a special command.

otherwise the plugin is working great, thanks a lot.

**Comment by nelsyeung** [comment]
Just wondering whether you have `set autoindent` in your `.vimrc`?

**Comment by lalonso-dev** [comment]
yes of course I have` set autoindent ` in my .`vimrc.`
like this is my [.vimrc](https://github.com/useralberto/configVim)
